# Use a lightweight Node.js image
FROM node:lts-alpine3.23
 
# Set working directory inside the container
WORKDIR /app
 
# Copy package files
COPY package*.json ./
 
# Install dependencies
RUN npm install
 
# Copy rest of the source code
COPY . .
  
# Expose create-react-app server port
EXPOSE 3000
 
# Run with start npm command
CMD ["npm", "start"]