services:
  # ─── SERVER SERVICE ───
  wolterwhite-server:
    build: 
      context: .
      dockerfile: Dockerfile.server
    container_name: wolterwhite_server_container
    ports:
      - "5555:5555"
    volumes:
      - ./data:/usr/src/wolterwhite/build/data
    restart: unless-stopped

  wolterwhite-web:
      build:
        context: .
        dockerfile: Dockerfile.web
      container_name: wolterwhite_web_container
      ports:
      - "5000:5000"
      environment:
      - SERVER_HOST=wolterwhite-server 
      - SERVER_PORT=5555 
      restart: unless-stopped
  # ─── CLIENT SERVICE ───
  wolterwhite-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: wolterwhite_client_container
    environment:
      - SERVER_HOST=wolterwhite-server
      - SERVER_PORT=5555 # Force it to talk to the server on port 5555
    stdin_open: true
    tty: true
    depends_on:
      - wolterwhite-server
    command: tail -f /dev/null