// megaStressTest.js
import fs from 'fs/promises';
import crypto from 'crypto';

const BASE_URL = "http://localhost:5000/api";

// --- CONFIGURATION ---
// --- CONFIGURATION ---
const TARGET_USERS = 500;           // Was 30
const TARGET_RESTAURANTS = 1000;    // Was 100
const PRODUCTS_PER_REST = 10;       // Was 3 (Total: 10,000 products)
const TARGET_ORDERS = 5000;         // Was 150
const TARGET_VIEWS = 100000;        // Was 3,000
const BATCH_SIZE = 500;             // Was 50 (This is the concurrency killer!)

// --- DATA DICTIONARIES ---
const adjectives = ["Quantum", "Nuclear", "Cosmic", "Neon", "Cyber", "Mega", "Ghost", "Savage", "Liquid", "Void"];
const nouns = ["Pizza", "Burger", "Sushi", "Tacos", "Waffle", "Steak", "Noodles", "Salad", "Wrap", "Donut"];
const cities = ["Tel Aviv", "Haifa", "Jerusalem", "Eilat", "Rishon LeZion", "Be'er Sheva"];

// --- STATE TRACKING ---
const db = { users: [], restaurants: [], products: [], orders: [] };
const stats = {
    users: { success: 0, fail: 0, time: 0 },
    restaurants: { success: 0, fail: 0, time: 0 },
    products: { success: 0, fail: 0, time: 0 },
    orders: { success: 0, fail: 0, time: 0 },
    views: { success: 0, fail: 0, time: 0 },
    search: { success: 0, fail: 0, time: 0 }
};

// --- HELPER: RANDOM GENERATORS ---
const rand = (arr) => arr[Math.floor(Math.random() * arr.length)];
const randId = () => crypto.randomBytes(4).toString('hex');

// --- HELPER: API CALLER ---
async function apiCall(endpoint, method = 'GET', body = null, userId = null) {
    const headers = { 'Content-Type': 'application/json' };
    if (userId) headers['X-User-Id'] = userId;

    const options = { method, headers };
    if (body) options.body = JSON.stringify(body);

    try {
        const res = await fetch(`${BASE_URL}${endpoint}`, options);
        let data = null;
        if (res.status !== 204) {
            try { data = await res.json(); } catch (e) { /* Ignore parsing error on empty body */ }
        }
        return { status: res.status, data, success: res.status >= 200 && res.status < 300 };
    } catch (error) {
        return { status: 500, success: false, error: error.message };
    }
}

// --- MAIN EXECUTION ---
async function runEpicStressTest() {
    console.log("🚀 INITIATING MEGA STRESS TEST...\n");
    const startTime = Date.now();

    // ==========================================
    // PHASE 1: USERS
    // ==========================================
    console.log(`[1/6] Creating ${TARGET_USERS} Users...`);
    const p1Start = Date.now();
    for (let i = 1; i <= TARGET_USERS; i++) {
        const userPayload = {
            username: `stress_user_${randId()}`,
            name: `Test User ${i}`,
            phone: `050-${Math.floor(1000000 + Math.random() * 9000000)}`,
            address: `${rand(cities)}`,
            password: "password123"
        };
        const res = await apiCall('/users', 'POST', userPayload);
        if (res.success && res.data) {
            // Assuming your server returns the created object with an 'id' or '_id'
            db.users.push(res.data.id || res.data._id || res.data.userId);
            stats.users.success++;
        } else {
            stats.users.fail++;
        }
    }
    stats.users.time = Date.now() - p1Start;
    // Filter out undefined just in case parsing failed
    db.users = db.users.filter(id => id);
    if (db.users.length === 0) return console.error("💥 FAILED: No users created. Aborting test.");

    // ==========================================
    // PHASE 2: RESTAURANTS
    // ==========================================
    console.log(`[2/6] Creating ${TARGET_RESTAURANTS} Restaurants...`);
    const p2Start = Date.now();
    for (let i = 1; i <= TARGET_RESTAURANTS; i++) {
        const restPayload = {
            name: `${rand(adjectives)} ${rand(nouns)} Hub ${randId()}`,
            phone: `03-${Math.floor(1000000 + Math.random() * 9000000)}`,
            email: `info_${randId()}@rest.com`,
            address: `${rand(cities)}`,
            hours: "10:00-23:00",
            description: "Autogenerated stress test restaurant."
        };
        const res = await apiCall('/restaurants', 'POST', restPayload, rand(db.users));
        if (res.success && res.data) {
            db.restaurants.push(res.data.id || res.data._id || res.data.restaurantId);
            stats.restaurants.success++;
        } else {
            stats.restaurants.fail++;
        }
    }
    stats.restaurants.time = Date.now() - p2Start;
    db.restaurants = db.restaurants.filter(id => id);
    if (db.restaurants.length === 0) return console.error("💥 FAILED: No restaurants created. Aborting.");

    // ==========================================
    // PHASE 3: PRODUCTS
    // ==========================================
    console.log(`[3/6] Populating Menu Products...`);
    const p3Start = Date.now();
    for (const restId of db.restaurants) {
        for (let i = 1; i <= PRODUCTS_PER_REST; i++) {
            const prodPayload = {
                pname: `${rand(adjectives)} ${rand(nouns)} v${i}`,
                pdescription: `Delicious auto-generated item.`,
                price: Math.floor(Math.random() * 100) + 10
            };

            const res = await apiCall(`/restaurants/${restId}/products`, 'POST', prodPayload, rand(db.users));

            if (res.success && res.data) {
                // Try to find the ID. Adjust this if your server uses a different key for the product ID!
                const extractedId = res.data.id || res.data._id || res.data.productId || res.data.pId;

                if (extractedId) {
                    db.products.push({ pid: extractedId, rid: restId });
                    stats.products.success++;
                } else {
                    console.error(`⚠️ Product created, but couldn't find the ID in response:`, res.data);
                    stats.products.fail++;
                }
            } else {
                console.error(`❌ Product POST failed (Status ${res.status}):`, res.error || res.data);
                stats.products.fail++;
            }
        }
    }
    stats.products.time = Date.now() - p3Start;

    // Safety Check: Did we actually save any products?
    if (db.products.length === 0) {
        console.error("\n💥 CRITICAL FAILURE: No products were saved to the local database.");
        console.error("Check the error logs above to see if the server rejected the requests or if the ID key is wrong.");
        return; // Abort the test safely
    }

    // ==========================================
    // PHASE 4: ORDERS
    // ==========================================
    console.log(`[4/6] Simulating ${TARGET_ORDERS} Orders...`);
    const p4Start = Date.now();
    for (let i = 1; i <= TARGET_ORDERS; i++) {
        const product = rand(db.products);

        // Extra safety check just in case
        if (!product) continue;

        const orderPayload = {
            restaurantId: product.rid,
            products: [product.pid],
            status: "pending"
        };
        const res = await apiCall('/orders', 'POST', orderPayload, rand(db.users));
        if (res.success) stats.orders.success++;
        else stats.orders.fail++;
    }
    stats.orders.time = Date.now() - p4Start;

    // ==========================================
    // PHASE 5: BOMBARDMENT (VIEWS)
    // ==========================================
    console.log(`[5/6] BOMBARDMENT! Sending ${TARGET_VIEWS} product view requests...`);
    const p5Start = Date.now();

    // Pick top 3 products to become "viral"
    const viralProducts = db.products.slice(0, 3);

    // We send requests in batches to actually stress concurrent handling
    let viewsCompleted = 0;
    while (viewsCompleted < TARGET_VIEWS) {
        const batch = [];
        for (let i = 0; i < BATCH_SIZE && viewsCompleted < TARGET_VIEWS; i++) {
            const target = rand(viralProducts);
            batch.push(apiCall(`/restaurants/${target.rid}/products/${target.pid}`, 'GET'));
            viewsCompleted++;
        }

        const results = await Promise.all(batch);
        results.forEach(r => r.success ? stats.views.success++ : stats.views.fail++);

        process.stdout.write(`\r      Progress: ${viewsCompleted}/${TARGET_VIEWS} views`);
    }
    console.log(); // Newline after progress bar
    stats.views.time = Date.now() - p5Start;

    // ==========================================
    // PHASE 6: SEARCH SPAM
    // ==========================================
    console.log(`[6/6] Smashing Search endpoints...`);
    const p6Start = Date.now();
    const searchTerms = ["Pizza", "Burger", "Mega", "Cosmic", "a", "e"];
    for (let i = 0; i < 50; i++) {
        const res = await apiCall(`/search/${rand(searchTerms)}`, 'GET');
        if (res.success) stats.search.success++;
        else stats.search.fail++;
    }
    stats.search.time = Date.now() - p6Start;

    // ==========================================
    // REPORT GENERATION
    // ==========================================
    const totalTime = ((Date.now() - startTime) / 1000).toFixed(2);
    console.log(`\n✅ Testing Complete in ${totalTime}s! Generating report...`);

    const reportContent = `
# 🚀 Server Stress Test Report
**Date:** ${new Date().toLocaleString()}
**Total Time Elapsed:** ${totalTime} seconds

## 📊 Summary of Phases

| Phase | Target Amount | ✅ Success | ❌ Failed | ⏱️ Time Taken (ms) |
|---|---|---|---|---|
| **Users (POST)** | ${TARGET_USERS} | ${stats.users.success} | ${stats.users.fail} | ${stats.users.time} |
| **Restaurants (POST)** | ${TARGET_RESTAURANTS} | ${stats.restaurants.success} | ${stats.restaurants.fail} | ${stats.restaurants.time} |
| **Products (POST)** | ${TARGET_RESTAURANTS * PRODUCTS_PER_REST} | ${stats.products.success} | ${stats.products.fail} | ${stats.products.time} |
| **Orders (POST)** | ${TARGET_ORDERS} | ${stats.orders.success} | ${stats.orders.fail} | ${stats.orders.time} |
| **Views (GET Bombardment)** | ${TARGET_VIEWS} | ${stats.views.success} | ${stats.views.fail} | ${stats.views.time} |
| **Search (GET)** | 50 | ${stats.search.success} | ${stats.search.fail} | ${stats.search.time} |

## 🧬 Database Yield
* **Unique Users Created:** ${db.users.length}
* **Unique Restaurants Created:** ${db.restaurants.length}
* **Total Products Inserted:** ${db.products.length}

## ⚡ Performance Notes
* **Average View Latency:** ~${(stats.views.time / stats.views.success || 0).toFixed(2)} ms per request (calculated via batching).
* **Throughput:** ${((stats.views.success + stats.orders.success + stats.products.success + stats.restaurants.success + stats.users.success) / (totalTime)).toFixed(2)} Requests / Second during full lifecycle.

*Report automatically generated by megaStressTest.js*
    `.trim();

    await fs.writeFile('report.md', reportContent, 'utf8');
    console.log(`\n🎉 DONE! Check the "report.md" file in this folder for your test results.`);
}

runEpicStressTest();